FROM node:24-slim

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

WORKDIR /app

# Copia só os arquivos de dependência primeiro (cache inteligente)
COPY package.json pnpm-lock.yaml ./

RUN pnpm install

# Depois copia o resto
COPY . .

EXPOSE 5173

CMD ["pnpm", "dev", "--host"]